### ISSUE TITLE
Fix some style heritage issue  

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/react-ape#36]
Currently, if isn't setting parent styles into the children it just uses the default styles, for example:

```jsx
<View style={{ color: 'orange' }}><Text/></View>
```

ˆ Text should use color orange instead of black (which is the default).

**Comment by JohnPaulHarold** [comment]
Is this kind of cascade what you want? Or is this just a special case for `<Text/>` only?

I checked the React Native behaviour and it doesn't do that there (least, not on an Expo snack). I'm not saying that you shouldn't do this, because RN said so, but I notice elsewhere RN is given as a guide to follow for implementation: Button, TextInput etc.

**Comment by raphamorim** [comment]
Hmm very good point @JohnPaulHarold , checked it myself in RN as well and it doesn't have heritage as the issue described. Closing this issue. Thanks for the comment.
